<?php

/**
 * BaseTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Tweets
 * @property Doctrine_Collection $TweetTagAssoc
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method Doctrine_Collection getTweets()        Returns the current record's "Tweets" collection
 * @method Doctrine_Collection getTweetTagAssoc() Returns the current record's "TweetTagAssoc" collection
 * @method Tag                 setName()          Sets the current record's "name" value
 * @method Tag                 setTweets()        Sets the current record's "Tweets" collection
 * @method Tag                 setTweetTagAssoc() Sets the current record's "TweetTagAssoc" collection
 * 
 * @package    twitter
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tag');
        $this->hasColumn('name', 'string', 140, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 140,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Tweet as Tweets', array(
             'refClass' => 'TweetTagAssoc',
             'local' => 'tag_id',
             'foreign' => 'tweet_id'));

        $this->hasMany('TweetTagAssoc', array(
             'local' => 'id',
             'foreign' => 'tag_id'));
    }
}