<?php

/**
 * BaseTweetTagAssoc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tweet_id
 * @property integer $tag_id
 * @property Tweet $Tweet
 * @property Tag $Tag
 * 
 * @method integer       getTweetId()  Returns the current record's "tweet_id" value
 * @method integer       getTagId()    Returns the current record's "tag_id" value
 * @method Tweet         getTweet()    Returns the current record's "Tweet" value
 * @method Tag           getTag()      Returns the current record's "Tag" value
 * @method TweetTagAssoc setTweetId()  Sets the current record's "tweet_id" value
 * @method TweetTagAssoc setTagId()    Sets the current record's "tag_id" value
 * @method TweetTagAssoc setTweet()    Sets the current record's "Tweet" value
 * @method TweetTagAssoc setTag()      Sets the current record's "Tag" value
 * 
 * @package    twitter
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTweetTagAssoc extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tweet_tag_assoc');
        $this->hasColumn('tweet_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tag_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tweet', array(
             'local' => 'tweet_id',
             'foreign' => 'id'));

        $this->hasOne('Tag', array(
             'local' => 'tag_id',
             'foreign' => 'id'));
    }
}