<?php

/**
 * TweetTagAssocTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TweetTagAssocTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TweetTagAssocTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TweetTagAssoc');
    }
}